# Generated by Django 6.0.2 on 2026-02-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='password_attempted',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
